<?php
get_header();
?>
<main>
    <?php
    get_template_part(
        'template-parts/home/hero'
    );
    get_template_part(
        'template-parts/home/la-firma'
    );
    get_template_part(
        'template-parts/home/nuestra-historia'
    );
    get_template_part(
        'template-parts/home/principios'
    );
    get_template_part(
        'template-parts/home/nuestro-equipo'
    );
    ?>
</main>
<?php
get_footer();
